name: Setup Baileys

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Pindahkan isi folder Baileys-main ke root
      - name: Move Baileys-main to root
        run: |
          shopt -s dotglob nullglob

          if [ -d "Baileys-main" ]; then
            mv Baileys-main/* .
            rm -rf Baileys-main
          fi

      # 4. Install dependencies
      - name: Install dependencies
        run: npm install

      # 5. Cek isi folder
      - name: Show files
        run: ls -R

      # 6. Jalankan bot (optional test)
      - name: Run bot
        run: node index.js
