name: Auto Extract ZIP

on:
  push

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          unzip -o Baileys-main.zip
          mv Baileys-main/* .
          rm -rf Baileys-main
          rm -f Baileys-main.zip

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git diff --staged --quiet || git commit -m "Extract Baileys source"
          git push
